name: Build Code

on:
  push:
    branches:
      - main  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Run commands
        run: |
          echo "Installing Python Packages"
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          echo "Installed all Packages"
          pyb
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact publist
          path: /home/runner/work/python-build-test/* 
          retention-days: 90
