name: Build Code

on:
  push:
    branches:
      - main  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Run commands
        run: |
          echo "Installing Python Packages"
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt || exit 1 # Stop on failure
          echo "Installed all Packages"
          pyb || exit 1 # Stop on failure
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_publish 
          path: /home/runner/work/python-build-test/python-build-test/result/*
          retention-days: 90
